---
title: "MEN1 in Adult and Pediatric AML"
author: "Jenny Smith"
date: "June 24, 2019"
output: html_document
---


```{r setup}
library(knitr)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=50),tidy=TRUE, fig.align='center', fig.height = 8, fig.width = 10)
knitr::opts_knit$set(root.dir = '/fh/fast/meshinchi_s/workingDir/TARGET/AML_TARGET/RNA/mRNAseq/analysis/2018.04.05_ROR1_MEN1_Waterfallplots_Expression/')
options(stringsAsFactors = FALSE)
```

```{r message=FALSE}
library(dplyr)
library(magrittr)
library(ggplot2)
library(stringr)
library(reshape2)
library(tidyr)
library(tibble)
library(ggpubr)
library(DeGSEA)
library(gridExtra)
getwd()
```

```{r}
source("~/scripts/RNAseq_Analysis/Waterfallplots/Waterfall_Barplot_Function_2017.05.22.r")
source("~/scripts/RNAseq_Analysis/DifferentialExpn_PathwayAnalysis/R/in_progress/ggplot_Themes_Function.r")
```

#Read in the expression data 

```{r}
TPMs <- readRDS("~/RNA_seq_Analysis/0000.00.03_Expression_Matrices/TARGET_AML_RBD_Kallisto_Quant_GeneLevel_TPM.RDS")

head(TPMs[,1:5])
```


#Read in the CDEs 

```{r}
Groups <- read.csv("~/reference_mapping-files/TARGET_AML_RBD_Cohorts_forDE_5.20.19.csv") %>% 
  add_row(USI=grep("^BM|^RO", colnames(TPMs), value=TRUE)) %>%
  mutate_at(vars(CBFA2T3.GLIS2.forDEGs:Rare.Fusions), .funs = ~ifelse(is.na(.), "NBM", .)) %>% 
  set_colnames(gsub(".forDEGs","",colnames(.))) %>%
  mutate(Categories=pheno_bars(., "USI", cols=c("CBFA2T3.GLIS2", "CBFB.MYH11", 
                                                "KMT2A.ELL", "KMT2A.MLLT1",
                                                "KMT2A.MLLT10","KMT2A.MLLT3",
                                                "KMT2A.MLLT4", "NUP98.KDM5A", 
                                                "NUP98.NSD1", "RUNX1.RUNX1T1"))) %>% 
  mutate(Categories=case_when(
    grepl("NBM", Categories) ~ "NBM", 
    grepl("OtherAML", Categories) & grepl("MLL", Cytogenetic.Category.1) ~ "KM2TA-X",
    grepl("OtherAML", Categories) & grepl("Normal", Cytogenetic.Category.1) ~ "Normal_Cyto", 
    grepl("OtherAML", Categories) & grepl("Other", Cytogenetic.Category.1) ~ "Other_Cyto", 
    TRUE ~ Categories))
  

head(Groups)
# tail(Groups)
dim(Groups)
```

```{r}
table(Groups$Categories)
```


#Waterfall plots 

```{r}
pheno1 <- Groups$Cytogenetic.Category.1 %>%
  set_names(Groups$USI)

pheno2 <- Groups$Cytogenetic.Category.2 %>% 
  gsub("Unknown","OtherAML",.) %>%
  set_names(Groups$USI)

pheno3 <- Groups$Rare.Fusions %>% 
  gsub("Unknown","OtherAML",.) %>%
  set_names(Groups$USI)

table(pheno1, useNA = "always")
table(pheno2, useNA = "always")
table(pheno3, useNA = "always")
```

```{r}
TPMs.subset <- TPMs[grep("ENSG00000133895", rownames(TPMs)), ]
rownames(TPMs.subset) <- "MEN1"
head(TPMs.subset[,1:5])
dim(TPMs.subset)
```

```{r }
MEN1.plots <- arrangeGrob(grobs=lapply(list(pheno1,pheno2,pheno3), 
                                       function(p) waterfallPlot(expnMatrix = TPMs.subset,  
                                                                geneName = "MEN1", 
                                                                phenoVector = p, 
                                                                unit = "TPM")), 
                          ncol = 3, nrow = 1)


# plot(MEN1.plots[[5]])
```

```{r fig.width=16, fig.height=4}
plot(MEN1.plots)
```

```{r }
# ggsave("TARGET_AML_MEN1_Expression_TPMs.pdf",MEN1.plots,width = 17, height = 4, units = "in")
```

```{r}
MEN1.data <- lapply(list(pheno1,pheno2,pheno3), 
                                       function(p) waterfallPlot(expnMatrix = TPMs.subset,  
                                                                geneName = "MEN1", 
                                                                phenoVector = p, 
                                                                unit = "TPM", 
                                                                returnData = TRUE)[[1]])

lapply(MEN1.data, head)
```


#Boxplots/Waterfall plots with TCGA and TARGET  

```{r}
TCGA_Targ <- get(load("~/RNA_seq_Analysis/0000.00.03_Expression_Matrices/TcgaTargetGtex_NormBlood_AML_rsem_geneSymbol_dupGenesRemoved_tpm.RData"))

head(TCGA_Targ[,1:5])
# dim(TCGA_Targ) 58,531 and 738  samples
```

```{r}
pheno.toil <- ifelse(grepl("GTEX", colnames(subset)), "Normal.WholeBlood", 
                     ifelse(grepl("TARGET", colnames(subset)), "TARGET.AML", "TCGA.AML")) %>%
  set_names(colnames(subset))

table(pheno.toil)
```

```{r}

TAR.TCGA.GTEX <- waterfallPlot(expnMatrix = subset,geneName = "ROR1",phenoVector =  pheno.toil, unit="TPM", returnData = TRUE) 

# tiff("ROR1_TCGA_TPM_waterfallplot.tiff", height = 5, width = 8, units = "in", res=600)
TAR.TCGA.GTEX$Plot +  ylim(0,8) +
  scale_fill_brewer(palette = "Dark2") +
  labs(title="ROR1 RNA-Seq Expression TARGET, TCGA, and GTEX")
# dev.off()
```

```{r}
TAR.TCGA.GTEX$Data %>% 
  group_by(Status) %>%
  summarise_at(vars(val), funs(mean,median,max,min))
  
```

```{r}
forDist <- subset %>%
  rownames_to_column("gene") %>%
  filter(gene == "ROR1") %>%
  select(-gene) %>%
  gather(var, value) %>%
  mutate(log2.TPM=log2(value+1)) %>%
  mutate(Group=ifelse(grepl("GTEX", var), "Normal.WholeBlood", 
                     ifelse(grepl("TARGET", var), "TARGET.AML", "TCGA.AML"))) %>%
  mutate(Group=factor(Group, levels=c("Normal.WholeBlood","TARGET.AML", "TCGA.AML" )))
  

# forDist
table(forDist$Group)
```

```{r}
comparisons <- list(c("Normal.WholeBlood","TARGET.AML"),
                    c("TARGET.AML", "TCGA.AML" ),
                    c("Normal.WholeBlood","TCGA.AML" ))

ggboxplot(forDist, x="Group", y="log2.TPM", color="Group", palette="jco") +
  stat_compare_means(comparisons = comparisons) +
  ylim(0,10) +
  stat_compare_means(label.y = 9.5)

```



